package communication;

public enum DC {

    NO_INFO,
    GET_ITEM_LIST,
    ADD_ITEMS,
    REMOVE_ITEMS,
    GET_ITEMS,
    SYNC_LISTS,
    SERVER_CONNECTION_ERROR,
    NO_ERROR, GENERAL_ERROR,
    CONNECTION_NOT_SETUP,
    DISCONNECT

}